# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8WvqKiRCyTtpW4QVf-mRHIb8iSt7Nd0
"""

from fastapi import FastAPI
import joblib
import numpy as np
import os

# --- Create the API application ---
app = FastAPI(title="Churn Prediction API")

# --- Load the saved model ---
model = joblib.load("churn_model.pkl")

@app.get("/")
def home():
    return {"message": "Churn Prediction API is running"}

@app.post("/predict")
def predict(data: dict):
    # Ensure keys match your incoming request
    features = np.array([[
        data["monthly_spend"],
        data["tenure_months"],
        data["support_calls"]
    ]])

    # Use predict_proba for probabilities
    churn_prob = model.predict_proba(features)[0][1]

    return {
        "churn_probability": round(float(churn_prob), 4)
    }